package game;

public enum GameState {
    START_SCREEN,
    OPEN_FIRST_CARDS,
    PLAYING,
    STRESS,
    STALEMATE,
    PLAYER1_WINS,
    PLAYER2_WINS,
    NO_VALID_MOVES_BOTH_PLAYERS_HAVE_CARDS_IN_DECK,
    NO_VALID_MOVES_PLAYER1_HAS_CARDS_IN_DECK,
    NO_VALID_MOVES_PLAYER2_HAS_CARDS_IN_DECK;
    public static GameState STATE = START_SCREEN;
}