version: '3.8'
services:
  stress:
    build: .
    ports:
      - "6080:6080"
    environment:
      - DISPLAY=:99
      - PULSE_SERVER=unix:/tmp/pulse/native
    volumes:
      - /tmp/pulse:/tmp/pulse
      - /dev/shm:/dev/shm
    privileged: true